name: inventary_go
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1
  cool_alert: ^2.0.1
  country_code_picker: ^3.0.0
  dropdown_search: ^5.0.6
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_barcode_scanner: ^2.0.0
  flutter_form_builder: ^9.2.1
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.1.0
  flutter_speed_dial: ^7.0.0
  flutter_spinbox: ^0.13.1
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_maps_flutter: ^2.5.3
  google_maps_flutter_android: ^2.7.0
  google_maps_flutter_platform_interface: ^2.6.0
  google_maps_place_picker_mb: ^3.1.2
  hexcolor: ^3.0.1
  http: ^1.2.0
  icons_launcher: ^2.1.7
  image_picker: ^1.0.7
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  lazy_load_scrollview: ^1.3.0
  location: ^6.0.1
  paginated_list: ^1.2.3
  permission_handler: ^11.3.1
  salomon_bottom_bar: ^3.3.2
  syncfusion_flutter_datagrid: ^24.2.9
  syncfusion_flutter_datepicker: ^24.2.7
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/
    # - assets/images/nuevoAssets/
    # - assets/images/filtros/
    # - assets/images/iconosFiltros/
    # - assets/sounds/
    # - .env
  uses-material-design: true
